version: "3.2"
services:
  redbot:
    container_name: redbot
    build:
      context: ./RedBotDocker
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./redbot:/data
    environment:
      TOKEN: ${TOKEN}
      PREFIX: ~
      TZ: America/Detroit
      PUID: 1000
  db:
    ports:
      - '5433:5433'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: quotes
    volumes:
      - ./data:/var/lib/postgresql/data
    command: -p 5433
  api:
    ports:
      - '8080:8080'
    build:
      context: ./RaiQuotes-V2
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5433/quotes